### ISSUE TITLE
OpenAPI set battery mode

### ISSUE THREAD

**Issue by Argosy87** [tijsverkoyen/HomeAssistant-FusionSolar#74] opened 2023-03-06 19:10 UTC
Hi, is it possible to set parameters trough the api in ha?
Like example the battery charge/discharge mode.

**Comment by tijsverkoyen** [comment] 2023-03-07 10:37
I think this is a duplicate of https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/59
If I am wrong: feel free to reopen this issue.

**Closed by tijsverkoyen** 2023-03-07 10:37 UTC
Labels: duplicate
