### ISSUE TITLE
Incorrect 0 values in some api queries

### ISSUE THREAD

**Issue by jvcsw** [tijsverkoyen/HomeAssistant-FusionSolar#138] opened 2024-01-17 22:10 UTC
**Describe the bug**
Some sensors returns 0 values breaking all statitiscs.

For exemple: total_lifetime_energy

** Debug information **
No traces found

** Are you using Kiosk or Northbound / OpenAPI mode?
  * [ ] Kiosk
  * [X] Northbound OpenAPI

**To Reproduce**

I don't know.

**Expected behavior**
Incremental values cannot be 0 when previous values were greater than 0.

**Screenshots**

![imagen](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/assets/37216513/33eeaddb-6f7c-41b3-89ef-1daba89554c7)

**Additional context**
I think that for some reason the api get fail and the sensors return 0.

**Comment by tijsverkoyen** [comment] 2024-01-18 07:55
Do you have the latest version installed?

**Comment by tijsverkoyen** [comment] 2024-01-18 07:56
Also, isn't this a duplicate of https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/135

**Comment by jvcsw** [comment] 2024-01-18 10:37
I have the latest, v3.0.2.

The problem is similar, I don't know if it's the same, because it returns 0 to me

**Comment by tijsverkoyen** [comment] 2024-01-24 16:53
@jvcsw would you be able to apply the changes from https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/142 on your local installation? And if so: would you be so kind to report if this fixes the issue.

**Comment by jvcsw** [comment] 2024-01-25 09:03
It's very hard to check if it works because it's a behavior that's beyond my reach. The error happened very occasionally. 

When I have time I do. Thanks.

**Comment by tijsverkoyen** [comment] 2024-01-26 16:01
@jvcsw thx, there is one change that should be removed. Can you reapply the changes please. Otherwise there might by problems with the current year and current month sensors.

Could you test this out for a few weeks, and let me know if there are issues? I would really appreciate it.

**Comment by jvcsw** [comment] 2024-02-05 08:58
Good morning.

I have seen these issues for the past few days. I hope they help you:

`Entity sensor.casa_total_lifetime_energy from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 4857.37 (4857.38) with last_updated set to 2024-02-03T19:57:29.584175+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

Entity sensor.current_year_inverter_yield from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 113.24 (113.3) with last_updated set to 2024-02-03T21:37:29.919071+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

Entity sensor.casa_total_current_year_energy from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 113.24 (113.3) with last_updated set to 2024-02-03T21:37:29.919464+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues

Entity sensor.lifetime_inverter_yield from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 4857.32 (4857.38) with last_updated set to 2024-02-03T21:37:29.920995+00:00. Please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues`

Error requesting FusionSolarOpenAPIDeviceRealKpiType data: 504 Server Error: Gateway Timeout for url: https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi

Error requesting FusionSolarOpenAPIDeviceRealKpiType data: 502 Server Error: Bad Gateway for url: https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi

Error requesting FusionSolarOpenAPIDeviceRealKpiType data: HTTPSConnectionPool(host='eu5.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /thirdData/getDevRealKpi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fff50d0>: Failed to establish a new connection: [Errno -3] Try again'))

Error requesting FusionSolarOpenAPIDeviceRealKpiType data: 500 Server Error: Internal Server Error for url: https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi

**Comment by danielhunt** [comment] 2024-02-05 09:10
I think this and #145 are related

**Comment by tijsverkoyen** [comment] 2024-02-07 15:27
I will not try to fix the glitches for Current Month or Current Year. Huawei FusionSolar should up their game and don't send wrong values.

I have created https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v3.0.3 which has the better handling for the glitches in Lifetime.

**Closed by tijsverkoyen** 2024-02-07 15:27 UTC
