### ISSUE TITLE
Not in coordinator data

### ISSUE THREAD

**Issue by yfyap69** [tijsverkoyen/HomeAssistant-FusionSolar#165] opened 2024-04-22 09:44 UTC
Having some trouble to get data to HA. Logs shown as per below:

This error originated from a custom integration.

Logger: custom_components.fusion_solar.fusion_solar.energy_sensor
Source: custom_components/fusion_solar/fusion_solar/energy_sensor.py:67
Integration: FusionSolar (documentation, issues)
First occurred: 16:28:40 (25 occurrences)
Last logged: 17:38:43

Attribute dailyEnergy not in coordinator data
Attribute monthEnergy not in coordinator data
Attribute yearEnergy not in coordinator data
Attribute cumulativeEnergy not in coordinator data

**Comment by yfyap69** [comment] 2024-04-22 09:45
More info from logs

This error originated from a custom integration.

Logger: custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api
Source: custom_components/fusion_solar/fusion_solar/kiosk/kiosk_api.py:46
Integration: FusionSolar (documentation, issues)
First occurred: 16:28:40 (8 occurrences)
Last logged: 17:38:43

Retrieving the data failed. Raw response: {"data":"neteco.pvms.systemSetting.notExist","success":false,"failCode":0}

**Comment by azelinc** [comment] 2024-04-23 08:12
i m having the same issues. i verified that kiosk url is working. Anyone else manage to still get this working?

**Comment by tijsverkoyen** [comment] 2024-04-24 06:33
> I m having the same issues (maybe not similar cause, because diff error message), it started 2-3 days ago. I have verified that kiosk url is working, managed to view it in the browser. Anyone else manage to still get this working?
> 
> 2024-04-19 12:15:21.430 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fusion_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant 2024-04-19 12:15:48.415 ERROR (MainThread) [custom_components.fusion_solar.sensor] Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='intl.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=xxxxxxxxxx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
> 
> (i ve masked the kiosk url with xxxx for privacy purpose)

The culprit in this case is `SSLCertVerificationError`. It seems like the SSL certificate of your kiosk instance is not valid. Or your system that is running Home Assistant is not able to validate it.

1. If you open the Kiosk url in your browser. Is the certificate valid? If not: contact Huawei.
2. Are you using the latest version of Home Assistant?
3. Is your Home Assistant running on an outdated operating system?

**Comment by tijsverkoyen** [comment] 2024-05-02 19:46
@yfyap69 Have you been able to resolve this?
I will close this issue for now. Feel free to reopen the issue if you think the problem is in this integration.

**Closed by tijsverkoyen** 2024-05-02 19:46 UTC
