### ISSUE TITLE
All Inverter and Meter entities return "Unknown"

### ISSUE THREAD

**Issue by ssorgatem** [tijsverkoyen/HomeAssistant-FusionSolar#73] opened 2023-03-02 14:57 UTC
Basically I cna only get the daily, monthly and yearly yields and little else. The rest of entities return "unknown" values.

![image](https://user-images.githubusercontent.com/108138/222462360-ebc3ee97-75d7-4d2f-af53-124132c4bbc0.png)

I'm on the https://region01eu5.fusionsolar.huawei.com/ region and m,y account is from a couple months ago. 
Maybe this is related to https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/68 ?

I don't know where to look for logs for this, I'm new to HA...

**Comment by tijsverkoyen** [comment] 2023-03-03 08:21
My first guess is that your installed did not give you enough permissions.
You can enable logging by going to Settings → Devices & Services. There you should see the "Fusion Solar" integration. If you click on the 3 dots there is a button "Enable debug logging". The logs can be found under Settings → System → Logs

**Comment by ssorgatem** [comment] 2023-03-03 18:12
That cannot be because I can get much more than that using this python module in my own scripts: https://github.com/EnergieID/FusionSolar

Now I have logs but they are both massive and contain sensitive data. What should I be looking for in there?

**Comment by ssorgatem** [comment] 2023-03-03 18:36
After playing around removing and re-adding the integration, now it reads some values it didn't before from the inverter: model ,location, device ID, etc. in general all static values, but no data of power or anything.

But I can get it through the API and through the app.

**Comment by tijsverkoyen** [comment] 2023-03-04 08:47
From what you are describing I think you are hitting the rate limiting.
In the logs there should be something like `Access frequency too high`. There is nothing much I can do about that. You can try to disable devices: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#disabling-devices

If there is nothing about the access frequency too high in the log. You can mail (`fusionsolar [at] Verkoyen.eu`) your OpenAPI credentials to me and I will try to debug.

**Comment by aretokas** [comment] 2023-03-06 10:07
The rate limiting thing would be my guess as well. I have the luxury of having an installer account so I can make as many API credentials as I need to test/develop. But up until I figured out what was going on I encountered very similar issues to what is described here.

@ssorgatem - Are you using the same credentials in multiple places? You mentioned other scripts, and you've potentially used Postman as well if you're accessing the API directly. If you're using the same API credentials across all of them you're 100% going to be hitting the rate limiting, especially on the real time, daily, monthly, yearly KPI endpoints.

**Comment by tijsverkoyen** [comment] 2023-03-06 13:52
@aretokas offtopic: but if you have an installer account: feel free to clarify the README with the steps that are needed to create an OPEN API account, and which settings should be activated.

**Comment by tijsverkoyen** [comment] 2023-03-10 12:38
@ssorgatem any update? Are you seeing the `Access frequency too high` error?

**Comment by tijsverkoyen** [comment] 2023-03-17 09:44
I will close this issue as there is no update. Feel free to reopen the issue.

**Closed by tijsverkoyen** 2023-03-17 09:44 UTC
Labels: waiting for feedback

**Comment by perezga** [comment] 2023-03-18 00:09
Im having same problem and testing myself with postman , the problem is the data map in the  response from Huawei is empty...it must be a bug in their side as the endpoints return success with some data but the important stiff is just missing.

**Comment by Argosy87** [comment] 2023-03-18 07:45
> Im having same problem so I tested myself with postman and the problem is the data map in the response from API is just empty...it must be a bug in their side as the endpoints return success with some data but the important stuff is just missing.

Just ask your installer to set the correct permissions to get the data.
If its empty and querry is succes you do not have the correct permissions on your account.

**Comment by perezga** [comment] 2023-03-18 08:14
As you can see, all permissions are enabled for the account. It is in spanish, but second line from the top reads 'plant data for realtime'.  The account should have permission unless expandind those permissions there is some disabled which I hvae no visibility

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aretokas** [comment] 2023-03-18 08:30
![image](https://user-images.githubusercontent.com/6782246/226094560-6ca725c0-0259-4c21-bf08-aa2ee57c55ac.png)

@perezga There definitely is the possibility that "All" has not been selected as per this screenshot. I cannot see your screenshot (I'm assuming it was an attachment to your email reply)

Here's a link to the part in the readme on what permissions should be required. Notice I've made a particular note of selecting "All" under each heading. Unfortunately the default view is collapsed and the default even after turning on a section is to not  select anything underneath it - so if your installer has just hit the slider to turn a section on, but not expanded and selected "All" - That will be your issue.

https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#if-you-know-your-installer

**Comment by aretokas** [comment] 2023-03-18 08:31
![image](https://user-images.githubusercontent.com/6782246/226094691-69843dcd-4695-4e95-9231-91ff9993a06b.png)

This is what it SHOULD look like.

**Comment by perezga** [comment] 2023-03-18 09:22
Thanks for the info. I will contact my installer to check it.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
