### ISSUE TITLE
Wondering if this could be changed: FusionSolr sensor names and existence

### ISSUE THREAD

**Issue by tschiex** [tijsverkoyen/HomeAssistant-FusionSolar#102] opened 2023-07-29 11:09 UTC
Tijs, two tiny comments:

1. in the devices, each sensor is printed with a dash, as "- Active power" while most (if not all) other extensions do not use a leading dash and would use "Active power" by default. This is purely aesthetical, but I like the second version better, also for consistency with all other extensions.
2. in my northbound API, I have selected only the statistics I know exist on my devices. For example, my inverter is a single-phase inverter, with 2MPTT so things like 'PV5 input current/voltage', 'MPPT 4 DC total yield', Phase C current' do not exist and I did not make them exportable in the northbound API. But they still appear as sensors in the extension. Would it be possible to detect that some sensors are not exported and then, not create the corresponding sensor? (Again, not crucial of course :-)

Thanks for the nice work anyway.

**Comment by tijsverkoyen** [comment] 2023-08-01 12:38
First of all: Thx for the sponsoring, really appreciated!

> 1. in the devices, each sensor is printed with a dash, as "- Active power" while most (if not all) other extensions do not use a leading dash and would use "Active power" by default. This is purely aesthetical, but I like the second version better, also for consistency with all other extensions.

I know, I should revise it. It was a dumb decision on my part as it was my first integration. In my case it was prepended with the station name. I will look into it when I find some time.

> 2. in my northbound API, I have selected only the statistics I know exist on my devices. For example, my inverter is a single-phase inverter, with 2MPTT so things like 'PV5 input current/voltage', 'MPPT 4 DC total yield', Phase C current' do not exist and I did not make them exportable in the northbound API. But they still appear as sensors in the extension. Would it be possible to detect that some sensors are not exported and then, not create the corresponding sensor? (Again, not crucial of course :-)

The problem is that the API returns all that data, and there is no real way of knowing if the value is (example) 0.0 because it is not present or the actual value at that point in time is 0.0.

You can only add the sensors you want to your dashboards in Home Assistant. I think you can also disable entities in Home Assistant. Maybe the later is sufficient for you?

I think you can disable

**Comment by tijsverkoyen** [comment] 2023-08-30 15:38
@tschiex about the first issue:
> in the devices, each sensor is printed with a dash, as "- Active power" while most (if not all) other extensions do not use a leading dash and would use "Active power" by default. This is purely aesthetical, but I like the second version better, also for consistency with all other extensions.

They all should be prepended with your Device name? It seems that Home Assistant is showing the text most on the right. So `10203009XXXX - Active power` is shown as `- Active power`. Can you check by clicking on the entity, at the top the full name should be shown.

I think the prefix with the Device name is beneficial for people with multiple devices / plants.

Or maybe your device name is empty?

**Comment by tijsverkoyen** [comment] 2023-09-19 11:16
I will close this issue as there as no feedback is provided.
Feel free to reopen if needed.

**Closed by tijsverkoyen** 2023-09-19 11:16 UTC
Labels: waiting for feedback
