### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by catalinbordan** [tijsverkoyen/HomeAssistant-FusionSolar#69] opened 2023-02-27 07:11 UTC
Hi,
Same as #60.
I just want to let you know, it did not fix it. Your changes in the code it should be before line no 67, no?

```
 if current_value == 'unavailable':
                    _LOGGER.info(
                        f'{self.entity_id}: not available.')
                    return
```

**Comment by tijsverkoyen** [comment] 2023-02-28 13:10
I can't reproduce this issue so it is really difficult to test. But I have changed the code. Will be included in the upcoming release.

**Closed** 2023-02-28 13:11 UTC
