### ISSUE TITLE
Error407 ACCESS_FREQUENCY_IS_TOO_HIGH

### ISSUE THREAD

**Issue by benztanji** [tijsverkoyen/HomeAssistant-FusionSolar#30] opened 2022-12-24 02:10 UTC
custom_components.fusion_solar.device_real_kpi_coordinator
Source: helpers/update_coordinator.py:168 
Integration: Fusion Solar ([documentation](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar), [issues](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues)) 
First occurred: 9:05:31 AM (1 occurrences) 
Last logged: 9:05:31 AM

Error fetching FusionSolarOpenAPIDeviceRealKpiType data: Error fetching data: Access frequency to high. failCode: 407, message: ACCESS_FREQUENCY_IS_TOO_HIGH

I used OpenApi mode
Server: https://intl.fusionsolar.huawei.com/

**Comment by mkosmida2** [comment] 2022-12-25 17:52
Duplicate of
https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/29

**Closed** 2022-12-28 09:56 UTC
