### ISSUE TITLE
Daily warning: fusion_solar has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by guus461** [tijsverkoyen/HomeAssistant-FusionSolar#43] opened 2023-01-28 06:49 UTC
My log shows this warning on a daily basis:

`[..] from integration fusion_solar has state class total_increasing, but its state is not strictly increasing.`

```
 Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:385
Integration: Sensor (documentation, issues)
First occurred: 06:10:10 (2 occurrences)
Last logged: 06:10:10

    Entity sensor.XXXX_total_current_month_energy from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 295.99 (304.48) with last_updated set to 2023-01-27T23:08:00.312625+00:00. Please report it to the custom integration author.
    Entity sensor.XXXX_total_lifetime_energy from integration fusion_solar has state class total_increasing, but its state is not strictly increasing. Triggered by state 2675.34 (2683.83) with last_updated set to 2023-01-27T23:08:00.312916+00:00. Please report it to the custom integration author.
```
And indeed, every day minutes after midnight I see the state **drops for one hour** and come back to the exact state before.

(Please note the time line; I am currently traveling 6 hours ahead of the HA instance at home)

![image](https://user-images.githubusercontent.com/14141936/215251261-93d5fd4c-26f8-4039-bab7-1a824c7edb63.png)

And a wider span, showing daily drops between (minutes after) midnight and 1 am:
![image](https://user-images.githubusercontent.com/14141936/215251671-463ff13b-588b-45ba-960b-472ba60cfa88.png)
_(Please note my +6 hours timezone difference when making the screenshot)_

I am using integration version 2.3.1
Home Assistant 2023.1.7 
Supervisor 2023.01.1 
Operating System 9.4 
Frontend-versie: 20230110.0 
HACS:  1.30.1

I can imagine this is not related to your integration but the source OpenAPI (FusionSolar / Huawei). Can you please advise?

**Comment by tijsverkoyen** [comment] 2023-01-29 14:25
Duplicate of https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/4

**Closed** 2023-01-29 14:25 UTC
Labels: duplicate
